-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGkUDbefbme2maF3g
WlDTslj0UeahdXLx+tmgQAbT9IKgCgYIKoZIzj0DAQehRANCAASrYXUiB73WyubV
rIgUQ7kdVac+CT2til8NzFa1qaMn5bpvGiWwgfzWD0NF1/W5DfJzufydRJ6vZJlG
6fZ8S9OG
-----END PRIVATE KEY-----