-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4PpqH/ZUsO6udfgh
0XJj+nDf4UzpHGwLx2k9gDbgigygCgYIKoZIzj0DAQehRANCAATV0nR5+LijieZG
npht5QYUtLqe8bawBgSvO0SmBt7gk8G92le2uHErGms24wQLLZceUoFck+ogyptt
bgdg8uUu
-----END PRIVATE KEY-----